---
format: gfm
metadata-files:
  - _metadata.yml
---

# {{< meta gh.repo >}}: {{< meta tagline >}}

{{< include /includes/_badges.qmd >}}

This contains information (in Danish and English) on how to work on the Danish
registers at Statistics Denmark (DST) for research purposes. The guide covers
many aspects of working with the registers, drawing from the experience of
working within the Steno Diabetes Center Aarhus.

Check out the [website](https://steno-aarhus.github.io/registers-guide/) for the
guide!

::: callout-tip
This website repository was generated from the
[`template-website`](https://github.com/seedcase-project/template-website)
Seedcase template :tada:
:::

## Contributing

Check out our [contributing document](CONTRIBUTING.md) for information on how to
contribute to the project, including how to set up your development environment.

Please note that this project is released with a [Contributor Code of
Conduct](CODE_OF_CONDUCT.md). By participating in this project you agree to
abide by its terms.

::: content-hidden
<!-- TODO: Unhide when there are more contributors -->
### Contributors

<!-- {{< include /includes/_contributors.qmd >}} -->
:::

## Licensing

This project is licensed under the [CC-BY-4.0 License](LICENSE.md).
