from_latest_tag = true
disable_changelog = true
disable_bump_commit = true
branch_whitelist = ["main"]
pre_bump_hooks = [
  # Quiet the log output of git-cliff, it is noisy.
  "RUST_LOG='none' uvx git-cliff --tag ",
  "uvx --from panache-cli panache format CHANGELOG.md --quiet",
  "git commit CHANGELOG.md -m 'build: 🔖 update version to  [skip ci]'",
]
post_bump_hooks = ["git push", "git push --tags"]

[commit_types]
refactor = { bump_patch = true }
perf = { bump_patch = true }
fix = { bump_patch = true }
feat = { bump_minor = true }
